### ISSUE TITLE
Custom init.rc script

### ISSUE THREAD

**Issue by apowers313** [TinkerBoard/android-6.0.1_kernel#1]
In `init.rc`, would it be possible to add a call to `/system/bin/boot.sh` or import `/system/etc/init/init.rc` to give users a hook into the boot process? It would make tinkering so much easier than having to modify the ROM to add new scripts to boot-up.

**Comment by alex3788** [comment]
Hi apowers313,

Please use TinkerOS_Android V13.12.0.43 image and you could use below command to push init.asus.sh that can do hook the boot process.

adb root
adb remount
adb push init.asus.sh /system/etc/init.asus.rc

**Comment by apowers313** [comment]
Thanks for the quick reply. I dropped this in to `/system/etc/init.asus.rc`:

```
on init
     export SYSTEMRC yes
```

However, after the system boots SYSTEMRC isn't set (as demonstrated by `echo $SYSTEMRC`). I've also tried `/system/etc/init/init.rc`, `/vendor/etc/init/init.rc`, and other various locations that [the Android docs say should work](https://android.googlesource.com/platform/system/core/+/master/init/README.md), but so far none have worked. Also, `dmesg` doesn't show any errors (at least not related to this :) ).

**Comment by alex3788** [comment]
Dear apowers313,

We will check this internally and let you know the result.

**Comment by alex3788** [comment]
Dear apowers313,

Sorry for my typo, /system/etc/init.asus.rc should be corrected as /system/etc/init.asus.sh

Ex:
`adb push init.asus.sh /system/etc/init.asus.rc`

About export variables in init.asus.sh shell script issue
Because a shell script runs in a child shell process, and only children of the child shell would inherit the export, so you can't do export variable through shell script.
